Lecture_3_DJango/airline/airline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flights/', include("flights.urls")),
]

Lecture_3_DJango/airline/flights/urls.py
from django.urls import path
from . import views

app_name = "flights"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:flight_id>", views.flight, name="flight")
]

Lecture_3_DJango/airline/flights/models.py
from django.db import models

# Create your models here.


#Airtport Model
class Airport(models.Model):
    code = models.CharField(max_length=64)
    city = models.CharField(max_length=64)
    def __str__(self):
        return f"{self.city} ({self.code})"


# Flight Model
class Flights(models.Model):
    origin =  models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination =models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration  = models.IntegerField()
    def __str__(self):
        return f"{self.id}: {self.origin} to {self.destination}"

Lecture_3_DJango/airline/flights/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Flights
# Create your views here.
def index(request):
    return render(request, "flights/index.html", {
        "flightlist":Flights.objects.all()
    })

def flight(request, flight_id) :
    flightInfo  =  Flights.objects.get(id=flight_id)
    # or  flightInfo  =  Flights.objects.get(pk=flight_id)
   
    return render(request, "flights/flight.html", {
        "flight":flightInfo
    })
    # return HttpResponse(flightInfo.origin)

Lecture_3_DJango/airline/flights/templates/flights/flight.html
<!DOCTYPE html>
<html>  
    <head>
        <title>
            My Airline
        </title>
    </head>

    <body>
      <h4>
            <a href="{% url 'flights:index'%}">
                Go Back
            </a>
      </h4>

      <h2>Flight {{flight.id}}</h2>
      <h2>{{flight.origin}}</h2>
      <h2>{{flight.destination}}</h2>
      <h2>{{flight.duration}}</h2>
    </body>

</html>

Lecture_3_DJango/airline/flights/templates/flights/index.html
<!DOCTYPE html>
<html>  
    <head>
        <title>
            My Airline
        </title>
    </head>

    <body>
       <table>
            <thead>
                <tr>
                    <th> Flight id </th>
                    <th> Origin </th>
                    <th> Destination </th>
                    <th> Duration </th>
                </tr>
            </thead>

            <tbody>
                {% for sflight in flightlist  %}
                        <tr>
                            <td> 
                                <a href="{% url 'flights:flight' sflight.id %}">
                                    {{sflight.id}}
                                </a>
                            </td>
                            <td> {{sflight.origin.city}} </td>
                            <td> {{sflight.destination.city}} </td>
                            <td> {{sflight.duration}} </td>
                        </tr>
                {% endfor %}
            </tbody>
       </table>
    </body>

</html>